[general]
problem_db="problems"
test_dir="danger"

[lang]
julia=["jl"]
python=["py"]
c=["c"]
"c++"=["cc","cpp"]
binary=["bin","exe"]
octave=["m"]


[submission]
sol_path=""               # 
lang=""                   # it 
user_id=0                 # Int
problem_id=""             # must be a unique string
sol_mode="app"            # prog is the classic stdin/stdout way, app is the solve(fin,fout) one
sender="other"            # cli, repl, other
test_id=""
test_dir=""
problem_dir=""            # the path to the act ptoblem (for convenience)
store=0

[process]
error=0
infoit="n/a"
validateit="n/a"
prepareit="n/a"
compileit="n/a"
runit="n/a"
reportit="n/a"
finalit="n/a"
