part1.in=["1.in","2.in","3.in","4.in","5.in","6.in"]
part1.out=["part1.1.out","part1.2.out","part1.3.out","part1.4.out","part1.5.out","part1.6.out"]

part2.in=["1.in","2.in","3.in","4.in","5.in","6.in"]
part2.out=["part2.1.out","part2.2.out","part2.3.out","part2.4.out","part2.5.out","part2.6.out"]
